baseURL = "https://www.soda.guide/"
languageCode = "en-us"
title = "The Soda Guide"

theme               = "introduction"
enforce_ssl         = true
builddrafts         = false                             # Include pages with draft status of true
canonifyurls        = true                              # Turns relative urls into absolute urls
# disqusshortname   = "xxx"                             # Enable Disqus for comments
# googleAnalytics   = "xxx"

[params]
    bloghead            = "Blog"                        # Full name shows on blog post pages
    firstname           = "Nathan"                # First name shows in introduction on main page
    tagline             = "I write short soda reviews on Twitter."       # Appears after the introduction
    introheight         = "fullheight"                       # Input either 'medium' or 'large' or 'fullheight'
    themestyle          = "light"                        # Choose 'light' or 'dark'
    #avatar              = "img/profile.jpg"             # Path to image in static folder eg. img/avatar.png, or comment out to remove
    #email               = "nathan@virtualmicropolis.com"         # Shows in contact section, or leave blank to omit
    localtime           = false                          # Show your current local time in contact section
    timezone            = "America/Chicago"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    dateform            = "Jan 2, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    cachebuster         = false                         # Add the current unix timestamp in query string for cache busting css assets (relevant in development mode)
    description         = "Sort soda and soft drink reviews."        # Max 160 characters show in search results
    faviconfile         = "img/fav.ico"
    pygmentsStyle       = "monokai"                     # Choose theme: https://help.farbox.com/pygments.html
    pygmentsCodeFences  = true
    footertext          = ""                            # Text to show in footer (overrides default text)
    fadein              = true                          # Turn on/off the fade-in effect

    showblog            = false                          # Show Blog section on home page
    showprojects        = false                          # Show Projects section on home page
    projectcolumns      = "3"                           # Choose "2" or "3" columns for projects section
    placeholderimg      = "/img/workday.jpg"            # For Projects without image
    showallposts        = false                         # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
    showlatest          = true                          # Show latest blog post summary
    sharebuttons        = true                          # On post pages, show share this social buttons

    # Share buttons
    sharetwitter        = false
    sharefacebook       = false
    sharepinterest      = false
    sharegoogleplus     = false

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
    url = "https://twitter.com/cavorter"
    icon = "twitter"

#[[params.social]]
#    url = "https://facebook.com/"
#    icon = "facebook"

#[[params.social]]
#    url = "https://linkedin.com/"
#    icon = "linkedin"